# Generated by Django 3.2.5 on 2021-07-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210719_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='base_stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='core.basestat'),
        ),
    ]
